import OpenAI from 'openai';
import { config } from './config';
import { ShellType } from './shell';

// Initialize OpenAI client for OpenRouter
const openai = new OpenAI({
  baseURL: 'https://openrouter.ai/api/v1',
  apiKey: config.openRouterApiKey,
});

export interface GenerateCommandOptions {
  query: string;
  shell: ShellType;
  model?: string;
}

/**
 * Generates a shell command from natural language query using OpenRouter AI
 * @param options The generation options
 * @returns The generated shell command
 */
export async function generateCommand(options: GenerateCommandOptions): Promise<string> {
  const { query, shell, model = config.defaultModel } = options;

  try {
    const response = await openai.chat.completions.create({
      model: model,
      messages: [
        {
          role: 'user',
          content: `Generate a ${shell} command for: ${query}. Return only the command without any explanation or markdown formatting.`,
        },
      ],
      temperature: 0.1, // Low temperature for consistent, deterministic output
      max_tokens: 200,  // Sufficient for most shell commands
    });

    const command = response.choices[0]?.message?.content?.trim();

    if (!command) {
      throw new Error('No command was generated by the AI model');
    }

    return command;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to generate command: ${error.message}`);
    }
    throw new Error('Failed to generate command: Unknown error occurred');
  }
}

/**
 * Validates if the generated command looks reasonable
 * @param command The generated command
 * @returns True if the command passes basic validation
 */
export function validateCommand(command: string): boolean {
  // Basic validation - command should not be empty and not contain suspicious content
  if (!command || command.length === 0) return false;
  if (command.length > 1000) return false; // Unreasonably long command

  // Check for potentially dangerous patterns (basic security)
  const dangerousPatterns = [
    /rm\s+-rf\s+\/[^\/]/,  // rm -rf / (root deletion)
    /:\(\)\{.*:.*\}\;/,    // Fork bomb patterns
    /shutdown\s+now/,      // Immediate shutdown
  ];

  for (const pattern of dangerousPatterns) {
    if (pattern.test(command)) {
      return false;
    }
  }

  return true;
}
